# Generated by Django 3.1.4 on 2021-12-27 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20211227_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='constance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
